league/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from rest_framework import routers

from league import views

admin.autodiscover()

router = routers.DefaultRouter()
router.register(r'matches', views.MatchViewSet)
router.register(r'players', views.PlayerViewSet)

urlpatterns = patterns(
    '',
    # Examples:
    # url(r'^$', 'kicker_league.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^admin/', include(admin.site.urls)),
    url(r'^', include(patterns(
        '',
        url(r'^$', views.IndexView.as_view(), name='index'),
        url(r'^set_mode$', views.set_mode, name='set_mode'),
        url(r'^players$', views.PlayerView.as_view(), name='players'),
        url(r'^players/top$', views.PlayerTop.as_view(), name='players_top'),
        url(r'^players/(?P<pk>\d+)$', views.PlayerDetailView.as_view(),
            name='player_detail'),
        url(r'^matches$', views.MatchView.as_view(), name='matches'),
        url(r'^matches/enter$', views.MatchCreate.as_view(),
            name='matches_enter'),
        url(r'^about$', views.about, name='about'),
        ), namespace='league')),
    url(r'api/', include(router.urls)),
)

league/models.py
from django.core.validators import MaxValueValidator
from django.db import models


class Player(models.Model):
    name = models.CharField(max_length=200)
    name.db_index = True
    mu = models.FloatField(default=25.0)
    sigma = models.FloatField(default=25. / 3.)
    rank = models.FloatField(default=0.0)
    rank.db_index = True

    attacker_mu = models.FloatField(default=25.0)
    attacker_sigma = models.FloatField(default=25. / 3.)
    attacker_rank = models.FloatField(default=0.0)
    attacker_rank.db_index = True

    defender_mu = models.FloatField(default=25.0)
    defender_sigma = models.FloatField(default=25. / 3.)
    defender_rank = models.FloatField(default=0.0)
    defender_rank.db_index = True

    class Meta:
        ordering = ['name']

    def __unicode__(self):
        return self.name

    def get_absolute_url(self):
        from django.core.urlresolvers import reverse
        return reverse('league:player_detail', args=[str(self.id)])

    def matches_attacker_count(self):
        return self.playerhistory_set.filter(was_attacker=True).count()

    def matches_defender_count(self):
        return self.playerhistory_set.filter(was_attacker=False).count()


class Match(models.Model):
    score_team1 = models.PositiveSmallIntegerField(
        validators=[MaxValueValidator(10)],
        choices=[(i, i) for i in xrange(11)])
    score_team2 = models.PositiveSmallIntegerField(
        validators=[MaxValueValidator(10)],
        choices=[(i, i) for i in xrange(11)])
    team1_player1 = models.ForeignKey(Player, related_name='+')
    team1_player2 = models.ForeignKey(Player, related_name='+')
    team2_player1 = models.ForeignKey(Player, related_name='+')
    team2_player2 = models.ForeignKey(Player, related_name='+')
    timestamp = models.DateTimeField(auto_now_add=True)
    timestamp.db_index = True

    class Meta:
        verbose_name_plural = "matches"

    def __unicode__(self):
        return '%s / %s vs. %s / %s (%d:%d)' % (
            self.team1_player1, self.team1_player2,
            self.team2_player1, self.team2_player2,
            self.score_team1, self.score_team2)


class PlayerHistory(models.Model):
    player = models.ForeignKey(Player)
    player.db_index = True
    mu = models.FloatField(default=25.0)
    sigma = models.FloatField(default=25. / 3.)
    rank = models.FloatField(default=0.0)
    match = models.ForeignKey(Match)

    was_attacker = models.BooleanField(default=False)

    seperate_mu = models.FloatField(default=25.0)
    seperate_sigma = models.FloatField(default=25. / 3.)
    seperate_rank = models.FloatField(default=0.0)

league/views.py
from django.db.models import Q
from django import forms
from django.shortcuts import render, redirect
from django.views import generic
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Field, HTML, Layout
from rest_framework import viewsets

from league.models import Match, Player, PlayerHistory
from league.serializers import MatchSerializer, PlayerSerializer


class IndexView(generic.ListView):
    def get_queryset(self):
        return Match.objects.order_by('-timestamp')[:10].select_related()


class MatchForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super(MatchForm, self).__init__(*args, **kwargs)
        self.fields['score_team1'].label = 'Score'
        self.fields['score_team2'].label = 'Score'
        self.fields['team1_player1'].label = 'Attacker'
        self.fields['team1_player2'].label = 'Defender'
        self.fields['team2_player1'].label = 'Attacker'
        self.fields['team2_player2'].label = 'Defender'

    class Meta:
        model = Match
        fields = [
            'score_team1', 'score_team2',
            'team1_player1', 'team1_player2',
            'team2_player1', 'team2_player2'
        ]

    def clean(self, *args, **kwargs):
        player_list = [v for k, v in self.cleaned_data.iteritems() if k in
                       ('team1_player1', 'team1_player2',
                        'team2_player1', 'team2_player2')]
        if len(player_list) > len(set(player_list)):
            raise forms.ValidationError('You have entered duplicate players.',
                                        code='duplicate')
        return self.cleaned_data


class MatchCreate(generic.CreateView):
    model = Match
    form_class = MatchForm

    fields = ('score_team1', 'team1_player1', 'team1_player2',
              'score_team2', 'team2_player1', 'team2_player2')

    def form_valid(self, form):
        from trueskill import Rating, rate
        match = form.save(commit=False)
        histories = []
        if match.score_team2 > match.score_team1:  # put winning team first
            (match.score_team1, match.team1_player1, match.team1_player2,
             match.score_team2, match.team2_player1, match.team2_player2) = \
            (match.score_team2, match.team2_player1, match.team2_player2,
             match.score_team1, match.team1_player1, match.team1_player2)
        player_list = (match.team1_player1, match.team1_player2,
                       match.team2_player1, match.team2_player2)
        ratings = [Rating(mu=p.mu, sigma=p.sigma) for p in player_list]
        seperate_ratings = [
            (Rating(mu=a.attacker_mu, sigma=a.attacker_sigma),
             Rating(mu=d.defender_mu, sigma=d.defender_sigma))
            for a, d in [player_list[0:2], player_list[2:4]]
        ]
        ranks = [match.score_team2 > match.score_team1,
                 match.score_team2 < match.score_team1]
        new_ratings = rate([ratings[0:2], ratings[2:4]], ranks=ranks)
        new_ratings = new_ratings[0] + new_ratings[1]
        new_seperate_ratings = rate(seperate_ratings, ranks=ranks)
        new_seperate_ratings = \
            new_seperate_ratings[0] + new_seperate_ratings[1]
        match.save()
        for i in range(len(player_list)):
            p = player_list[i]
            s = new_seperate_ratings[i]
            p.mu = new_ratings[i].mu
            p.sigma = new_ratings[i].sigma
            p.rank = p.mu - 3 * p.sigma
            h = PlayerHistory(match=match, player=p,
                              mu=p.mu, sigma=p.sigma, rank=p.rank,
                              seperate_mu=s.mu, seperate_sigma=s.sigma,
                              seperate_rank=(s.mu - 3 * s.sigma))

            if not i % 2:
                h.was_attacker = True
                p.attacker_mu = s.mu
                p.attacker_sigma = s.sigma
                p.attacker_rank = s.mu - 3 * s.sigma
            else:
                h.was_attacker = False
                p.defender_mu = s.mu
                p.defender_sigma = s.sigma
                p.defender_rank = s.mu - 3 * s.sigma

            p.save()
            p.old_mu = ratings[i].mu
            p.old_sigma = ratings[i].sigma
            p.old_rank = p.old_mu - 3 * p.old_sigma
            histories.append(h)
        PlayerHistory.objects.bulk_create(histories)

        context = {
            'match': match,
            'player_list': player_list,
            'ratings': ratings,
        }
        return render(self.request, 'league/match_enter_success.html', context)

    def get_form(self, *args, **kwargs):
        form = super(MatchCreate, self).get_form(*args, **kwargs)
        form.helper = FormHelper(form)
        form.helper.form_class = 'row'
        form.helper.label_class = 'col-lg-3'
        form.helper.field_class = 'col-lg-9'
        form.helper.layout = Layout(
            HTML("""
    <div class="col-sm-6">
        <div class="form-horizontal">
            <h3 class="text-center">Party 1</h3>
                 """),
            Field('score_team1'),
            Field('team1_player1'),
            Field('team1_player2'),
            HTML("""
        </div>
    </div>
    <div class="col-sm-6">
        <div class="form-horizontal">
            <h3 class="text-center">Party 2</h3>
                 """),
            Field('score_team2'),
            Field('team2_player1'),
            Field('team2_player2'),
            HTML("""
        </div>
        <button type="submit" class="btn btn-primary pull-right">
            Submit match results</button>
    </div>
                 """)
        )
        return form


class MatchView(generic.ListView):

    template_name = 'league/match_history.html'
    paginate_by = 100

    def get_context_data(self, **kwargs):
        context = super(MatchView, self).get_context_data(**kwargs)
        context['player_list'] = self.player_list
        context['selected_player'] = self.selected_player
        # we want to reuse the player objects
        p_dict = self.player_dict
        for m in context['match_list']:
            m._team1_player1_cache = p_dict.get(m.team1_player1_id)
            m._team1_player2_cache = p_dict.get(m.team1_player2_id)
            m._team2_player1_cache = p_dict.get(m.team2_player1_id)
            m._team2_player2_cache = p_dict.get(m.team2_player2_id)
        return context

    def get_queryset(self):
        self.player_list = Player.objects.all()
        self.player_dict = {p.pk: p for p in self.player_list}
        id = self.request.GET.get('player')
        try:
            id = int(id)
        except Exception:
            pass
        self.selected_player = self.player_dict.get(id)
        if self.selected_player:
            matches = Match.objects.order_by('-timestamp').filter(
                Q(team1_player1=self.selected_player) |
                Q(team1_player2=self.selected_player) |
                Q(team2_player1=self.selected_player) |
                Q(team2_player2=self.selected_player))
        else:
            self.selected_player = None
            matches = Match.objects.order_by('-timestamp')

        return matches


class PlayerView(generic.ListView):
    def get_queryset(self):
        mode = self.request.COOKIES.get('m', 'c')
        if mode == 'a':
            return Player.objects.order_by('-attacker_rank')
        elif mode == 'd':
            return Player.objects.order_by('-defender_rank')
        else:
            return Player.objects.order_by('-rank')


class PlayerTop(generic.ListView):
    template_name = 'league/player_top.html'

    def get_queryset(self):
        mode = self.request.COOKIES.get('m', 'c')
        if mode == 'a':
            players = Player.objects.order_by('-attacker_rank')[:10]
        elif mode == 'd':
            players = Player.objects.order_by('-defender_rank')[:10]
        else:
            players = Player.objects.order_by('-rank')[:10]
        for player in players:
            player.history = player.playerhistory_set.select_related(
                'match').order_by('match__timestamp')
        return players


class PlayerDetailView(generic.DetailView):
    queryset = Player.objects.all()

    def get_context_data(self, **kwargs):
        context = super(PlayerDetailView, self).get_context_data(**kwargs)
        context['history'] = PlayerHistory.objects.filter(
            player=context['player']).select_related('match').order_by(
            'match__timestamp')
        return context


class MatchViewSet(viewsets.ReadOnlyModelViewSet):
    queryset = Match.objects.order_by('-timestamp').select_related()
    serializer_class = MatchSerializer


class PlayerViewSet(viewsets.ReadOnlyModelViewSet):
    queryset = Player.objects.all()
    serializer_class = PlayerSerializer


def about(request):
    return render(request, 'league/about.html')


def set_mode(request):
    url = request.GET.get('url', 'league:index')
    mode = request.GET.get('mode', 'c')
    response = redirect(url)
    response.set_cookie('m', value=mode)
    return response

league/templates/league/about.html
{% extends 'league/base.html' %}
{% block navigation_about %}
<li class="active"><a href="#">About</a></li>
{% endblock %}
{% block content %}
<h1>About</h1>

<p>kicker-league is an open-source table football tracking / rating system.</p>

<p>It uses a rating algorithm developed by the research division of a well-known
software corporation from Redmond.  The skill of the player is quantified from
Bayesian inference.  kicker-league uses a ready-made implementation of the
algorithm in python, which is <a href="http://trueskill.org/">openly
available</a></p>

<h2>Get the Code</h2>

<p>kicker-league is currently developed on GitHub.</p>

<p>You can find the repository
at <a href="https://github.com/caladrel/trueskill_kicker">
    https://github.com/caladrel/trueskill_kicker</a></p>

<h2>Copyright and License</h2>

<p>Copyright 2014 kicker-league.</p>

<p>Licensed under the Apache License, Version 2.0 (the "License"); you may not
use this work except in compliance with the License. You may obtain a copy of
the License in the LICENSE file, or at:</p>

<p><a href="http://www.apache.org/licenses/LICENSE-2.0">
    http://www.apache.org/licenses/LICENSE-2.0</a></p>

<p>Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License
for the specific language governing permissions and limitations under the
License.</p>
{% endblock %}

league/templates/league/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Die QI-Kickerliga</title>
    <link rel="stylesheet" href="//netdna.bootstrapcdn.com/bootstrap/3.3.1/css/bootstrap.min.css">
    <link rel="stylesheet" href="//netdna.bootstrapcdn.com/bootstrap/3.3.1/css/bootstrap-theme.min.css">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no">
    <style type="text/css">
body {
  padding-top: 70px;
}

.asteriskField {
    display: none;
}
th.num {
    text-align: right;
}
td.num {
    text-align: right;
    font-family: Menlo,Monaco,Consolas,"Courier New",Monospace;
}
    </style>
    {% block header %}{% endblock %}
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="{% url 'league:index' %}">
                    QI Kickerliga</a>
            </div>
            <div class="collapse navbar-collapse">
                {% block navigation %}
                <ul class="nav navbar-nav">
                    {% block navigation_home %}
                    <li><a href="{% url 'league:index' %}">Home</a></li>
                    {% endblock %}
                    {% block navigation_matches %}
                    <li><a href="{% url 'league:index' %}">Matches</a></li>
                    {% endblock %}
                    {% block navigation_players %}
                    <li><a href="{% url 'league:players' %}">Players</a></li>
                    {% endblock %}
                    {% block navigation_top %}
                    <li><a href="{% url 'league:players_top' %}">Top ten</a></li>
                    {% endblock %}
                    {% block navigation_simulator %}
                    <li><a href="/simulator">Simulator</a></li>
                    {% endblock %}
                    {% block navigation_about %}
                    <li><a href="{% url 'league:about' %}">About</a></li>
                    {% endblock %}
                </ul>
                <ul class="nav navbar-nav navbar-right">
                    {% load simplecookie_state_selector %}
                    {% state_selector 'c' c='Combined mode' a='Attacker mode' d='Defender mode' %}
                </ul>
                {% endblock %}
            </div><!--/.nav-collapse -->
        </div>
    </div>
    <div class="container">
        {% block content %}{% endblock %}
    </div>
    <script src="//code.jquery.com/jquery.js"></script>
    <script src="//netdna.bootstrapcdn.com/bootstrap/3.3.1/js/bootstrap.min.js"></script>
</body>
</html>

league/templates/league/base_matches.html
{% extends 'league/base.html' %}
{% block navigation_matches %}
<li class="active"><a href="#">Matches</a></li>
{% endblock %}

league/templates/league/base_players.html
{% extends 'league/base.html' %}
{% block navigation_players %}
<li class="active"><a href="{% url 'league:players' %}">Players</a></li>
{% endblock %}

league/templates/league/match_enter_success.html
{% extends 'league/base_matches.html' %}
{% load cycle from future %}
{% block content %}
<h1>Match results</h1>
<ul class="nav nav-tabs">
    <li><a href="{% url 'league:index' %}">Recent results</a></li>
    <li><a href="{% url 'league:matches' %}">Show all results</a></li>
    <li class="active"><a href="#">Enter results</a></li>
</ul>
<h2>New match entered</h2>
<h3>{{ match }}</h3>
<p>The player statistics have changed as following:</p>
<ul>
{% for player in player_list %}
    <li>{{ player.name }} ({% cycle 'Attacker' 'Defender' %})</li>
    <ul>
        <li>rank: {{ player.old_rank|floatformat:2 }}
            &rarr; {{ player.rank|floatformat:2 }}</li>
        <li>µ: {{ player.old_mu|floatformat:2 }}
            &rarr; {{ player.mu|floatformat:2 }}</li>
        <li>σ: {{ player.old_sigma|floatformat:2 }}
            &rarr; {{ player.sigma|floatformat:2 }}</li>
    </ul>
{% endfor %}
</ul>
<ul class="nav nav-pills">
    <li><a href="{% url 'league:matches_enter' %}">Enter another match</a></li>
    <li><a href="{% url 'league:index' %}">Back to recent matches</a></li>
</ul>
{% endblock %}

league/templates/league/match_form.html
{% extends 'league/base_matches.html' %}
{% block content %}
<h1>Match results</h1>
<ul class="nav nav-tabs">
    <li><a href="{% url 'league:index' %}">Recent results</a></li>
    <li><a href="{% url 'league:matches' %}">Show all results</a></li>
    <li class="active"><a href="#">Enter results</a></li>
</ul>
{% load crispy_forms_tags %}
{% crispy form %}
{% endblock %}

league/templates/league/match_list.html
{% extends 'league/base_matches.html' %}
{% block content %}
<h1>Match results</h1>
<ul class="nav nav-tabs">
    <li class="active"><a href="#">Recent results</a></li>
    <li><a href="{% url 'league:matches' %}">Show all results</a></li>
    <li><a href="{% url 'league:matches_enter' %}">Enter results</a></li>
</ul>
<div class="panel panel-default">
    <div class="panel-heading">Recent matches</div>
    <div class="table-responsive">
        <table class="table table-striped">
            <tr>
                <th>Team 1</th>
                <th>Team 2</th>
                <th>Score</th>
                <th>Date</th>
            </tr>
            {% for match in match_list %}
                <tr>
                    <td><a href="{{ match.team1_player1.get_absolute_url }}">
                            {{ match.team1_player1.name }}</a> /
                        <a href="{{ match.team1_player2.get_absolute_url }}">
                            {{ match.team1_player2.name }}</a></td>
                    <td><a href="{{ match.team2_player1.get_absolute_url }}">
                            {{ match.team2_player1.name }}</a> /
                        <a href="{{ match.team2_player2.get_absolute_url }}">
                            {{ match.team2_player2.name }}</a></td>
                    <td>{{ match.score_team1 }}:{{ match.score_team2 }}</td>
                    <td>{{ match.timestamp }}</td>
                </tr>
            {% endfor %}
        </table>
    </div>
</div>
{% endblock %}

league/templates/league/player_detail.html
{% extends 'league/base_players.html' %}
{% load staticfiles %}
{% block header %}
<link rel="stylesheet" href="{% static "league/rickshaw.min.css" %}">
<script src="//code.jquery.com/jquery.js"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/d3/3.5.2/d3.min.js"></script>
<script src="{% static "league/rickshaw.min.js" %}"></script>
<style>
.rickshaw_legend {
    position: absolute;
    bottom: 10px;
    right: 10px;
    background-color: rgba(64,64,64,0.7);
}
.rickshaw_legend .action {
    opacity: 0.7;
    color: #fff;
}
</style>
{% endblock %}
{% block content %}
<h2>{{ player.name }}</h2>
<div class="row">
    <div class="col-md-4">
        <div class="panel panel-default">
            <div class="panel-heading">Combined statistics</div>
            <ul class="list-group">
                <li class="list-group-item">
                    rank: {{ player.rank|floatformat:2 }}
                </li>
                <li class="list-group-item">
                    µ: {{ player.mu|floatformat:2 }}
                </li>
                <li class="list-group-item">
                    σ: {{ player.sigma|floatformat:2 }}
                </li>
                <li class="list-group-item">
                    matches played: {{ player.playerhistory_set.count }}
                </li>
            </ul>
        </div>
    </div>
    <div class="col-md-4">
        <div class="panel panel-default">
            <div class="panel-heading">Attacker statistics</div>
            <ul class="list-group">
                <li class="list-group-item">
                    rank<sub>attacker</sub>: {{ player.attacker_rank|floatformat:2 }}
                </li>
                <li class="list-group-item">
                    µ<sub>attacker</sub>: {{ player.attacker_mu|floatformat:2 }}
                </li>
                <li class="list-group-item">
                    σ<sub>attacker</sub>: {{ player.attacker_sigma|floatformat:2 }}
                </li>
                <li class="list-group-item">
                    matches played: {{ player.matches_attacker_count }}
                </li>
            </ul>
        </div>
    </div>
    <div class="col-md-4">
        <div class="panel panel-default">
            <div class="panel-heading">Defender statistics</div>
            <ul class="list-group">
                <li class="list-group-item">
                    rank<sub>defender</sub>: {{ player.defender_rank|floatformat:2 }}
                </li>
                <li class="list-group-item">
                    µ<sub>defender</sub>: {{ player.defender_mu|floatformat:2 }}
                </li>
                <li class="list-group-item">
                    σ<sub>defender</sub>: {{ player.defender_sigma|floatformat:2 }}
                </li>
                <li class="list-group-item">
                    matches played: {{ player.matches_defender_count }}
                </li>
            </ul>
        </div>
    </div>
</div>
<div class="panel panel-default">
    <div class="panel-heading">historical data</div>
    <div class="panel-body">
        <div id="dummy"></div>
        <div id="chart"><div id="legend"></div></div>
    </div>
</div>
<script>

var series = [
        { color: '#848f39', name: 'defender', data: [
        {% for entry in history %}
        {% if not entry.was_attacker %}
        { x: {{ entry.match.timestamp| date:'U' }}, y: {{ entry.seperate_rank }} },
        {% endif %}
        {% endfor %}
        ]},
        { color: '#963b20', name: 'attacker', data: [
        {% for entry in history %}
        {% if entry.was_attacker %}
        { x: {{ entry.match.timestamp| date:'U' }}, y: {{ entry.seperate_rank }} },
        {% endif %}
        {% endfor %}
        ]},
        { color: '#2f254a', name: 'combined', data: [
        {% for entry in history %}
        { x: {{ entry.match.timestamp| date:'U' }}, y: {{ entry.rank }} },
        {% endfor %}
        ]},
    ];

var graph = new Rickshaw.Graph({
    element: document.querySelector("#chart"),
    renderer: 'line',
    series: series,
    padding: { left: 0.05 },
    interpolation: 'bundle'
});

var x_axis = new Rickshaw.Graph.Axis.Time( { graph: graph } );
var y_axis = new Rickshaw.Graph.Axis.Y( { graph: graph } );
var legend = new Rickshaw.Graph.Legend( { graph: graph,
       element: document.querySelector("#legend") } );
var shelving = new Rickshaw.Graph.Behavior.Series.Toggle({
    graph: graph,
    legend: legend
});

var resize = function() {
    dummy = document.querySelector("#dummy");
    graph.configure({ width: chart.clientWidth, height: 600 });
	graph.render();
}

window.addEventListener('resize', resize);
resize();
</script>
<ul class="nav nav-pills">
    <li>
    <a href="{% url 'league:players' %}">Back to player overview</a>
    </li>
    <li>
    <a href="{% url 'league:matches' %}?player={{ player.id }}">
        Show all matches involving {{ player.name }}</a>
    </li>
</ul>
{% endblock %}

league/templates/league/player_top.html
{% extends 'league/base.html' %}
{% load staticfiles %}
{% block navigation_top %}
<li class="active"><a href="{% url 'league:players_top' %}">Top Ten</a></li>
{% endblock %}
{% block header %}
<link rel="stylesheet" href="{% static "league/rickshaw.min.css" %}">
<script src="//code.jquery.com/jquery.js"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/d3/3.5.2/d3.min.js"></script>
<script src="{% static "league/rickshaw.min.js" %}"></script>
<style>
.rickshaw_legend {
    position: absolute;
    bottom: 10px;
    right: 10px;
    background-color: rgba(64,64,64,0.7);
}
.rickshaw_legend .action {
    opacity: 0.7;
    color: #fff;
}
</style>
{% endblock %}
{% block content %}
<h1>Top ten</h1>
<div class="panel panel-default">
    <div class="panel-heading">historical data</div>
    <div class="panel-body">
        <div id="dummy"></div>
        <div id="chart"><div id="legend"></div></div>
    </div>
</div>
<script>

var palette = new Rickshaw.Color.Palette({ scheme: 'classic9'});
{% load simplecookie_state_selector %}
{% get_state 'c' as mode %}
{% if mode == 'd' %}
var series = [
    {% for player in player_list %}
    {
    color: palette.color(),
    name: '{{ player.name }}\
        <a href="{{ player.get_absolute_url }}">\
        <span class="action glyphicon glyphicon-share-alt"></span>\
        </a>',
    data: [
    {% for entry in player.history %} {% if not entry.was_attacker %}
    { x: {{ entry.match.timestamp| date:'U' }}, y: {{ entry.seperate_rank }} },
    {% endif %} {% endfor %}
    ]
    },
    {% endfor %}
];
{% elif mode == 'a' %}
var series = [
    {% for player in player_list %}
    {
    color: palette.color(),
    name: '{{ player.name }}\
        <a href="{{ player.get_absolute_url }}">\
        <span class="action glyphicon glyphicon-share-alt"></span>\
        </a>',
    data: [
    {% for entry in player.history %} {% if entry.was_attacker %}
    { x: {{ entry.match.timestamp| date:'U' }}, y: {{ entry.seperate_rank }} },
    {% endif %} {% endfor %}
    ]
    },
    {% endfor %}
];
{% else %}
var series = [
    {% for player in player_list %}
    {
    color: palette.color(),
    name: '{{ player.name }}\
        <a href="{{ player.get_absolute_url }}">\
        <span class="action glyphicon glyphicon-share-alt"></span>\
        </a>',
    data: [
    {% for entry in player.history %}
    { x: {{ entry.match.timestamp| date:'U' }}, y: {{ entry.rank }} },
    {% endfor %}
    ]
    },
    {% endfor %}
];
{% endif %}

var graph = new Rickshaw.Graph({
    element: document.querySelector("#chart"),
    renderer: 'line',
    series: series,
    padding: { left: 0.05 },
    interpolation: 'bundle'
});

var x_axis = new Rickshaw.Graph.Axis.Time( { graph: graph } );
var y_axis = new Rickshaw.Graph.Axis.Y( { graph: graph } );
var legend = new Rickshaw.Graph.Legend( { graph: graph,
       element: document.querySelector("#legend") } );
var shelving = new Rickshaw.Graph.Behavior.Series.Toggle({
    graph: graph,
    legend: legend
});

var resize = function() {
    dummy = document.querySelector("#dummy");
    graph.configure({ width: chart.clientWidth, height: 600 });
	graph.render();
}

window.addEventListener('resize', resize);
resize();
</script>
<ul class="nav nav-pills">
    <li>
    <a href="{% url 'league:players' %}">Back to player overview</a>
    </li>
</ul>
{% endblock %}

league/templates/league/state_selector.html
<li class="dropdown">
<a href="#" class="dropdown-toggle" data-toggle="dropdown">{{ current_name }}<b class="caret"></b></a>
    <ul class="dropdown-menu">
        {% for key, name in choices.items %}
        <li>
            <a href="{% url 'league:set_mode' %}?mode={{ key }}&url={{ url|urlencode:'' }}">
                {{ name }}
            </a>
        </li>
        {% endfor %}
    </ul>
</li>